### ISSUE TITLE
variants data structure

### ISSUE THREAD

**Issue by calkan** [calkan/tardis#37]
see:
https://github.com/calkan/tardis/blob/master/variants.h

do we need anything else? Also see the commented question.

**Comment by calkan** [comment]
@fhormozd : can I get an answer, please?

**Comment by calkan** [comment]
also do we really need scores for each library separately for each sample?

**Comment by fhormozd** [comment]
How about a score for the cluster? I think we need to have a score (i.e. heuristcScore).
To calculated the likelihood of seeing that reads assumping the SV is true...

**Comment by calkan** [comment]
float/double/int? likelihood sounds like float/double.

**Comment by calkan** [comment]
I want to call it confidence score. Ok?

**Comment by fhormozd** [comment]
"confidence score" sound great and I think double should be good.

**Comment by calkan** [comment]
You want precision then? Ok.
